preImaging:
  steps:
    - setupSerialEM
    - setHighmagCountingMode
    - loadGrid
    - setupFrames
    - openColumnValve
    - resetState
postHighMag:
  steps:
    - resetAFISimageShift
    - refineZLP
    - collectHardwareDark
    - flashColdFEG
    - recenterBeam
    - zeroImageShift:
        save_beam_tilt: False